apiVersion: "v1"
kind: "Pod"
metadata:
  namespace: jenkins-slave
  labels:
    pipeline: jenkinsfile
    jenkins: slave
spec:
  containers:
    - name: 'node-14'
      image: node:14
      command: ["sleep", "7200"]
    - name: 'fortify-sca'
      image: registry.gitlab.com/sogeti_a4s/images/scancentral-client/fortify-scancentralclient:22.2.1
      args: ["sleep", "7200"]
      env:
        - name: CLIENT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: scancentral
              key: client-auth-token
        - name: WORKER_AUTH_TOKEN
          value: ""    
        - name: CA_CERTS_PASSWORD
          value: "changeit"
    - name: 'ssc-cli'
      image: registry.gitlab.com/sogeti_a4s/secdojo-containers-v2/fortify-cli:3.0
      command: ["sleep", "7200"]
      resources:
        requests:
          cpu: "0.1"
          memory: "512Mi"
        limits:
          cpu: "0.1"
          memory: "512Mi"
    - name: 'nexus-cli'
      image: sonatype/nexus-iq-cli 
      command: ["sleep", "7200"]
      resources:
        requests:
          cpu: "0.1"
          memory: "1024Mi"
        limits:
          cpu: "0.2"
          memory: "1024Mi"
    - name: 'owasp-dep-check'
      image: owasp/dependency-check
      imagePullPolicy: Always
      command: ["sleep", "7200"]
  imagePullSecrets:
  - name: regcred

